// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Platform {
  Booking = 'Booking',
  Airbnb = 'Airbnb',}

export interface Ingatlan {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Title: string;
    FeaturedImage: { data: Media[] };
    Platform?: Platform;
    Owner: string;
    OwnerImage?: { data: Media[] };
    Rating?: number;
    IngatlanLink?: string;
  };
}
export interface Ingatlan_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title: string;
  FeaturedImage: Media[];
  Platform?: Platform;
  Owner: string;
  OwnerImage?: Media[];
  Rating?: number;
  IngatlanLink?: string;
}

export interface Ingatlan_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title: string;
  FeaturedImage: number[];
  Platform?: Platform;
  Owner: string;
  OwnerImage?: number[];
  Rating?: number;
  IngatlanLink?: string;
}

export interface Ingatlan_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title: string;
  FeaturedImage: AdminPanelRelationPropertyModification<Media>[];
  Platform?: Platform;
  Owner: string;
  OwnerImage?: AdminPanelRelationPropertyModification<Media>[];
  Rating?: number;
  IngatlanLink?: string;
}
