// Interface automatically generated by schemas-to-ts

export interface CsomagOpcio {
  Opcio?: string;
  Tartalmazza?: boolean;
}
export interface CsomagOpcio_Plain {
  Opcio?: string;
  Tartalmazza?: boolean;
}

export interface CsomagOpcio_NoRelations {
  Opcio?: string;
  Tartalmazza?: boolean;
}

