// Interface automatically generated by schemas-to-ts

export interface Csomag {
  Nev: string;
  Opcio1?: string;
  Opcio2?: string;
  Opcio3?: string;
  Opcio4?: string;
  Opcio5?: string;
  Gomb?: string;
  Kiemelt?: boolean;
}
export interface Csomag_Plain {
  Nev: string;
  Opcio1?: string;
  Opcio2?: string;
  Opcio3?: string;
  Opcio4?: string;
  Opcio5?: string;
  Gomb?: string;
  Kiemelt?: boolean;
}

export interface Csomag_NoRelations {
  Nev: string;
  Opcio1?: string;
  Opcio2?: string;
  Opcio3?: string;
  Opcio4?: string;
  Opcio5?: string;
  Gomb?: string;
  Kiemelt?: boolean;
}

