// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';

export interface FooterFelettCta {
  Cta_cim: string;
  Cta_szoveg?: string;
  Cta_gomb?: string;
  Kep?: { data: Media };
}
export interface FooterFelettCta_Plain {
  Cta_cim: string;
  Cta_szoveg?: string;
  Cta_gomb?: string;
  Kep?: Media;
}

export interface FooterFelettCta_NoRelations {
  Cta_cim: string;
  Cta_szoveg?: string;
  Cta_gomb?: string;
  Kep?: number;
}

