// Interface automatically generated by schemas-to-ts

export interface FooterFelettCta {
  Cta_cim: string;
  Cta_szoveg?: string;
  Cta_gomb?: string;
}
export interface FooterFelettCta_Plain {
  Cta_cim: string;
  Cta_szoveg?: string;
  Cta_gomb?: string;
}

export interface FooterFelettCta_NoRelations {
  Cta_cim: string;
  Cta_szoveg?: string;
  Cta_gomb?: string;
}

