// Interface automatically generated by schemas-to-ts

export interface Cegadatok {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Email?: string;
    Telefonszam: string;
    Cim: string;
    Facebook_url?: string;
    Twitter_url?: string;
    Instagram_url?: string;
    locale: string;
    localizations?: { data: Cegadatok[] };
  };
}
export interface Cegadatok_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Email?: string;
  Telefonszam: string;
  Cim: string;
  Facebook_url?: string;
  Twitter_url?: string;
  Instagram_url?: string;
  locale: string;
  localizations?: Cegadatok[];
}

export interface Cegadatok_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Email?: string;
  Telefonszam: string;
  Cim: string;
  Facebook_url?: string;
  Twitter_url?: string;
  Instagram_url?: string;
  locale: string;
  localizations?: Cegadatok[];
}

export interface Cegadatok_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Email?: string;
  Telefonszam: string;
  Cim: string;
  Facebook_url?: string;
  Twitter_url?: string;
  Instagram_url?: string;
  locale: string;
  localizations?: Cegadatok[];
}
