// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Blog {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Cim: string;
    Kivonat: string;
    Szoveg: any;
    Kep: { data: Media };
    Datum: Date;
    Szerzo: string;
    locale: string;
    localizations?: { data: Blog[] };
  };
}
export interface Blog_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Cim: string;
  Kivonat: string;
  Szoveg: any;
  Kep: Media;
  Datum: Date;
  Szerzo: string;
  locale: string;
  localizations?: Blog[];
}

export interface Blog_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Cim: string;
  Kivonat: string;
  Szoveg: any;
  Kep: number;
  Datum: Date;
  Szerzo: string;
  locale: string;
  localizations?: Blog[];
}

export interface Blog_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Cim: string;
  Kivonat: string;
  Szoveg: any;
  Kep: AdminPanelRelationPropertyModification<Media>;
  Datum: Date;
  Szerzo: string;
  locale: string;
  localizations?: Blog[];
}
