// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Szolgaltatas {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Title: string;
    Content: string;
    ShortDescription: string;
    Ikon?: { data: Media };
  };
}
export interface Szolgaltatas_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title: string;
  Content: string;
  ShortDescription: string;
  Ikon?: Media;
}

export interface Szolgaltatas_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title: string;
  Content: string;
  ShortDescription: string;
  Ikon?: number;
}

export interface Szolgaltatas_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title: string;
  Content: string;
  ShortDescription: string;
  Ikon?: AdminPanelRelationPropertyModification<Media>;
}
