// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';

export interface KapcsolatKartya {
  Telefonszam?: string;
  Szoveg?: string;
  Ikon?: { data: Media };
  Email?: string;
  Cim?: string;
  Link_szoveg?: string;
  Link_url?: string;
}
export interface KapcsolatKartya_Plain {
  Telefonszam?: string;
  Szoveg?: string;
  Ikon?: Media;
  Email?: string;
  Cim?: string;
  Link_szoveg?: string;
  Link_url?: string;
}

export interface KapcsolatKartya_NoRelations {
  Telefonszam?: string;
  Szoveg?: string;
  Ikon?: number;
  Email?: string;
  Cim?: string;
  Link_szoveg?: string;
  Link_url?: string;
}

