// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';

export interface BemutatkozasSzekcio {
  Cim: any;
  Alcim?: string;
  Tartalom: any;
  Gomb_szoveg?: string;
  Kep?: { data: Media };
}
export interface BemutatkozasSzekcio_Plain {
  Cim: any;
  Alcim?: string;
  Tartalom: any;
  Gomb_szoveg?: string;
  Kep?: Media;
}

export interface BemutatkozasSzekcio_NoRelations {
  Cim: any;
  Alcim?: string;
  Tartalom: any;
  Gomb_szoveg?: string;
  Kep?: number;
}

