// Interface automatically generated by schemas-to-ts

import { GyikTartalom } from './GyikTartalom';
import { GyikTartalom_Plain } from './GyikTartalom';
import { GyikTartalom_NoRelations } from './GyikTartalom';

export interface GyakoriKerdesek {
  Cim: string;
  Gyik_tartalom: GyikTartalom[];
}
export interface GyakoriKerdesek_Plain {
  Cim: string;
  Gyik_tartalom: GyikTartalom_Plain[];
}

export interface GyakoriKerdesek_NoRelations {
  Cim: string;
  Gyik_tartalom: GyikTartalom_NoRelations[];
}

