// Interface automatically generated by schemas-to-ts

export interface GyikTartalom {
  Gyik_kerdes?: string;
  Gyik_valasz?: any;
}
export interface GyikTartalom_Plain {
  Gyik_kerdes?: string;
  Gyik_valasz?: any;
}

export interface GyikTartalom_NoRelations {
  Gyik_kerdes?: string;
  Gyik_valasz?: any;
}

