// Interface automatically generated by schemas-to-ts

export interface Velemeny {
  Nev: string;
  Munka_tipusa?: string;
  Velemeny: any;
}
export interface Velemeny_Plain {
  Nev: string;
  Munka_tipusa?: string;
  Velemeny: any;
}

export interface Velemeny_NoRelations {
  Nev: string;
  Munka_tipusa?: string;
  Velemeny: any;
}

